{{- if .Values.manifests.deployment_argo_ui }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-ui
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-ui-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-ui-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-ui-cluster-role
subjects:
  - kind: ServiceAccount
    name: argo-ui
    namespace: {{ $.Release.Namespace }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: argo-ui
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: argo-ui
  template:
    metadata:
      labels:
        app: argo-ui
    spec:
      serviceAccountName: argo-ui
      containers:
        - name: argo-ui
{{ tuple $ "argo_ui" | include "helm-toolkit.snippets.image" | indent 10 }}
          env:
            - name: ARGO_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: IN_CLUSTER
              value: "true"
            - name: ENABLE_WEB_CONSOLE
              value: "false"
            - name: BASE_HREF
              value: /
{{- end }}
