# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

images:
  tags:
    argo_ui: docker.io/argoproj/argoui:v2.2.1
    argo_workflow: docker.io/argoproj/workflow-controller:v2.2.1
    argo_executor: docker.io/argoproj/argoexec:v2.2.1
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
    image_repo_sync: docker.io/docker:17.07.0
  pull_policy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

pod:
  resources:
    enabled: false

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - argo-image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    image_repo_sync:
      services:
        - endpoint: internal
          service: local_image_registry

endpoints:
  cluster_domain_suffix: cluster.local
  local_image_registry:
    name: docker-registry
    namespace: docker-registry
    hosts:
      default: localhost
      internal: docker-registry
      node: localhost
    host_fqdn_override:
      default: null
    port:
      registry:
        node: 5000

manifests:
  cluster_role_argo_aggreate_to_admin: true
  cluster_role_argo_aggreate_to_edit: true
  cluster_role_argo_aggreate_to_view: true
  configmap_workflow_controller_configmap: true
  custom_resource_definition: true
  deployment_argo_ui: true
  deployment_workflow_controller: true
  service_argo_ui: true
