kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keystone-db-backup-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
